
CREATE TABLE COMPANY
(
  ID      varchar(200) NOT NULL COMMENT 'ID',
  NAME    varchar(200) NOT NULL COMMENT '이름',
  AGE     int          NULL     COMMENT '나이',
  ADDRESS varchar(200) NULL     COMMENT '주소',
  SALARY  int          NOT NULL COMMENT '월급',
  PRIMARY KEY (ID)
) COMMENT '회사 구성원';

CREATE TABLE DEPARTMENT
(
  ID     varchar(200) NOT NULL COMMENT '부서 ID',
  DEPT   varchar(200) NOT NULL COMMENT '부서',
  EMP_ID varchar(200) NOT NULL COMMENT '회사 ID',
  PRIMARY KEY (ID)
);

ALTER TABLE DEPARTMENT
  ADD CONSTRAINT FK_COMPANY_TO_DEPARTMENT
    FOREIGN KEY (EMP_ID)
    REFERENCES COMPANY (ID);
