
CREATE TABLE COMPANY
(
  ID      varchar(200) NOT NULL COMMENT 'ID',
  NAME    varchar(200) NOT NULL COMMENT '이름',
  AGE     int          NULL     COMMENT '나이',
  ADDRESS varchar(200) NULL     COMMENT '주소',
  SALARY  int          NOT NULL COMMENT '월급',
  PRIMARY KEY (ID)
) COMMENT '회사 구성원';

CREATE TABLE COMPANY_DEPT
(
  COMPANY_ID varchar(200) NOT NULL COMMENT 'ID',
  DEPT_ID    varchar(200) NOT NULL COMMENT '부서 ID'
) COMMENT '관계 테이블';

CREATE TABLE DEPARTMENT
(
  ID   varchar(200) NOT NULL COMMENT '부서 ID',
  DEPT varchar(200) NOT NULL COMMENT '부서',
  PRIMARY KEY (ID)
) COMMENT '부서 공통';

ALTER TABLE COMPANY_DEPT
  ADD CONSTRAINT FK_COMPANY_TO_COMPANY_DEPT
    FOREIGN KEY (COMPANY_ID)
    REFERENCES COMPANY (ID);

ALTER TABLE COMPANY_DEPT
  ADD CONSTRAINT FK_DEPARTMENT_TO_COMPANY_DEPT
    FOREIGN KEY (DEPT_ID)
    REFERENCES DEPARTMENT (ID);
